### ISSUE TITLE
Cannot use in NodeJS without overwriting package.json entries

### ISSUE THREAD

**Issue by tpo-celum** [imgly/psd-importer#2]
I'd like to use the psd-importer in a **Node** environment, which according to the readme is possible.

Looking at node_modules folder after installing the importer in my project I can see the following structure: a `browser.js` file and a `node.js` file.

![image](https://github.com/user-attachments/assets/470414d4-1611-4fb1-9cbf-7c48dc3f8919)

Currently, **in order to use the node.js** file I have to make the following patches to the package.json of the psd-importer:
 - change the module, types and exports section to refer to the node files instead of the browser ones
 - change the type field value from "module" to "commonjs", because the node.js file is written as a commonjs module

---

In addition, in light of the above the NodeJS Quick-Start is quite confusing with the `// We currently only support ES Modules in NodeJS` comment.

![image](https://github.com/user-attachments/assets/89fbb6b5-36f3-4d4b-8050-dc3e50ffc09f)

**Comment by mirko314** [comment]
Thanks for reporting this issue @tpo-celum. We are looking into this and let you know once we finished our investigation.

**Comment by bene-starzengruber** [comment]
hey @mirko314  - is there already an update on this issue?

**Comment by mirko314** [comment]
Hey @bene-starzengruber ,
due to current sickness season we were only just able to push out an release candidate for you to test.
Would you mind trying out if the new version `0.0.4-rc.0` works for you?
In this version, we would just release the same package for node/web with a ESModules version and a CommonJS version.

**Comment by tpo-celum** [comment]
Hi @mirko314,
Thank you for the rc version, the package.json looks good, we tested it out and it works well!

**Comment by mirko314** [comment]
Happy to hear that! 
We just published the official version 0.0.4 now that includes the fix!
